# Generated by Django 5.2.4 on 2025-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0002_alter_agencyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
