# Generated by Django 5.2.4 on 2025-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0003_agencyprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprofile',
            name='license_document',
            field=models.ImageField(upload_to='agency/licenses/'),
        ),
        migrations.AlterField(
            model_name='agencyprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='agency/profile_pics/'),
        ),
    ]
