# Generated by Django 5.2.4 on 2025-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0004_alter_agencyprofile_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
