# Generated by Django 5.2.4 on 2025-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0005_agencyprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
