# Generated by Django 5.2.4 on 2025-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0006_remove_agencyprofile_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
