# Generated by Django 5.2.4 on 2026-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0007_agencyprofile_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprofile',
            name='license_document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyprofile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
