# Generated by Django 5.2.4 on 2025-08-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
