# Generated by Django 5.2.4 on 2025-09-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_customuser_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
