# Generated by Django 5.2.4 on 2025-11-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 11, 19, 15, 10, 53, 214875, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='resend_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
