# Generated by Django 5.2.4 on 2025-09-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0005_agencyprofile_created_at'),
        ('bookings', '0002_booking_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_bookings', to='agency_app.agencyprofile'),
        ),
    ]
