# Generated by Django 5.2.4 on 2025-11-22 11:22

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_booking_status_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('ON_HAND', 'On Hand'), ('ONLINE', 'Online')], default=core.constants.PaymentMethod['ON_HAND'], max_length=20),
        ),
    ]
