# Generated by Django 5.2.4 on 2025-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_kids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
