# Generated by Django 5.2.4 on 2025-12-13 09:54

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_no_of_adults_booking_no_of_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUND_FAILED', 'Refund Failed')], default=core.constants.PaymentStatus['PENDING'], max_length=20),
        ),
    ]
