# Generated by Django 5.2.4 on 2025-12-29 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0007_agencyprofile_stripe_account_id'),
        ('bookings', '0008_alter_booking_payment_status'),
        ('packages', '0002_alter_package_price_package_package_price_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='booking_amount_positive'),
        ),
    ]
