# Generated by Django 5.2.4 on 2026-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_booking_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('agency', 'Agency'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
