# Generated by Django 5.2.4 on 2025-12-20 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0007_agencyprofile_stripe_account_id'),
        ('bookings', '0008_alter_booking_payment_status'),
        ('packages', '0001_initial'),
        ('reviews', '0002_review_rating_between_1_and_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking'),
        ),
    ]
