# Generated by Django 5.2.4 on 2025-12-29 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0007_agencyprofile_stripe_account_id'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='package_price_positive'),
        ),
    ]
