# Generated by Django 5.2.4 on 2026-01-13 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_price_package_package_price_positive'),
        ('recommendations', '0003_interest_packageinterest_userinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interaction', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='packageinterest',
            index=models.Index(fields=['interest'], name='recommendat_interes_e6804e_idx'),
        ),
        migrations.AddIndex(
            model_name='packageinterest',
            index=models.Index(fields=['package'], name='recommendat_package_1f2ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['package', 'action'], name='recommendat_package_376f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['created_at'], name='recommendat_created_d7e264_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user'], name='recommendat_user_id_ee8bae_idx'),
        ),
        migrations.AddConstraint(
            model_name='interest',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_interest_name'),
        ),
    ]
