# Generated by Django 5.2.4 on 2025-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=10, help_text='Percentage of total amount charged as platform fee', max_digits=5)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum fee charged if percentage is lower.', max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
            },
        ),
    ]
