# Generated by Django 5.2.4 on 2025-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfee',
            name='active',
        ),
        migrations.AddField(
            model_name='platformfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
